# Generated by Django 3.2.15 on 2022-10-30 08:39

import django.core.validators
from django.db import migrations, models
import exam_30_10_22.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SPORTS', 'Sports Car'), ('PICKUP', 'Pickup'), ('CROSSOVER', 'Crossover'), ('MINIBUS', 'Minibus'), ('OTHER', 'Other')], max_length=10)),
                ('model', models.CharField(max_length=20, validators=[exam_30_10_22.web.validators.validate_string_min_2_symbols])),
                ('year', models.PositiveIntegerField(validators=[exam_30_10_22.web.validators.validate_year_between_1980_and_2049])),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
